### ISSUE TITLE
Read bigsparser matrix

### ISSUE THREAD

**Issue by meliamne** [privefl/bigsparser#10]
Hey,

I'm super happy to see someone working on an on disk sparse matrix for R.
For my particular use case I am wondering if there is a way to read/connect these matrices back into a new R session from their backing file.

Kind regards,
Daan Moechars

**Comment by privefl** [comment]
Yes, you can just save the object in an rds file using saveRDS() and use readRDS() in the other session.
I wonder if I have made a `$save()` method to do that (as for the dense FBMs); if not, maybe I should.

**Comment by meliamne** [comment]
Great,

Thank you very much for the directions!
They help me out a lot.

Kind regards,
Daan Moechars

**Comment by privefl** [comment]
Actually, the `$save()` method is already there.
https://github.com/privefl/bigsparser/blob/master/R/SFBM.R#L105-L108
