### ISSUE TITLE
Accessing matrix rows/cols in R

### ISSUE THREAD

**Issue by meliamne** [privefl/bigsparser#11]
Hi,

sorry to gunk up your issues section with questions.
Is there a way to get data from the on disk sparse matrix into memory?
I am basically looking for a way to read a column or row into memory for visualization, and perhaps do some sub-setting like mat[1:10,2]? 
Apologies if I am missing something obvious or misunderstanding the purpose of the package. 

Kind regards,
Daan Moechars

**Comment by privefl** [comment]
Asking questions and new features is part of what issues are for, no worries.

I have thought about implementing accessors that would give you e.g. a sparse matrix.
Just didn't have the use yet, so haven't do it for now.

Accessing a subset of columns would be fairly easy. However, (efficiently) accessing a subset of rows would be a bit trickier.
I could maybe implement something quickly that is not too efficient for now.

**Comment by meliamne** [comment]
If implementing a way to access rows and columns would not be too much hassle, the ability to do so would be incredibly helpful to me!

**Comment by privefl** [comment]
Which format are you using? The compact one, or the normal one?

**Comment by meliamne** [comment]
I'm using the regular one.

**Comment by privefl** [comment]
I should be done implementing this tomorrow morning.
Will let you know.

**Comment by privefl** [comment]
You can try the new version
`remotes::install_github("privefl/bigsparser")`

**Comment by meliamne** [comment]
Hey took me a while to get back on this. This is exactly what I needed. Thank you!

**Comment by privefl** [comment]
BTW the new version is on CRAN now.
