### ISSUE TITLE
create_file function

### ISSUE THREAD

**Issue by subhomoyghosh** [privefl/bigsparser#6]
Where from can we get the crearte_file() function used [here](https://github.com/privefl/bigsparser/blob/master/src/write-indval.cpp)

**Comment by privefl** [comment]
Look at the top of the file:
https://github.com/privefl/bigsparser/blob/master/src/write-indval.cpp#L3

This is from package {rmio}.

**Comment by subhomoyghosh** [comment]
Sorry, I didn't realize that rmio is a package. I was looking at mio but couldn't find it. Got it, thanks! I do have another question but that is not related to any issue. I am closing the issue now!
